596649639987,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (167, 2018-09-18 16:22:21.128437-05, 1, 2018-09-18 16:22:21.12846-05, 0, 5, null, 2018-09-18 14:16:44-05, ordered, 1156, 8900.00, 1421.01, 0.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '0.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 128460, tzinfo=<UTC>), 'order_number': 1156, 'status': 'ordered', 'tax': '1421.01', 'client_id': None, 'created_by': 1, 'date': '2018-09-18T14:16:44-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 128437, tzinfo=<UTC>), 'total': '8900.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
596405518387,The phone number into order is not a valid number
596171915315,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (166, 2018-09-18 16:22:21.060827-05, 1, 2018-09-18 16:22:21.060872-05, 0, 5, null, 2018-09-18 10:39:52-05, ordered, 1149, 0.00, 0.00, 0.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '0.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 60872, tzinfo=<UTC>), 'order_number': 1149, 'status': 'ordered', 'tax': '0.00', 'client_id': None, 'created_by': 1, 'date': '2018-09-18T10:39:52-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 60827, tzinfo=<UTC>), 'total': '0.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
596168769587,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (165, 2018-09-18 16:22:21.002097-05, 1, 2018-09-18 16:22:21.002127-05, 0, 5, null, 2018-09-17 23:30:50-05, ordered, 1148, 8900.00, 1421.01, 0.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '0.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 2127, tzinfo=<UTC>), 'order_number': 1148, 'status': 'ordered', 'tax': '1421.01', 'client_id': None, 'created_by': 1, 'date': '2018-09-17T23:30:50-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 21, 2097, tzinfo=<UTC>), 'total': '8900.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
596155629619,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (164, 2018-09-18 16:22:20.944554-05, 1, 2018-09-18 16:22:20.944592-05, 0, 5, null, 2018-09-18 10:40:09-05, ordered, 1147, 0.00, 0.00, 0.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '0.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 944592, tzinfo=<UTC>), 'order_number': 1147, 'status': 'ordered', 'tax': '0.00', 'client_id': None, 'created_by': 1, 'date': '2018-09-18T10:40:09-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 944554, tzinfo=<UTC>), 'total': '0.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
596047036467,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (163, 2018-09-18 16:22:20.896612-05, 1, 2018-09-18 16:22:20.896636-05, 0, 5, null, 2018-09-17 20:17:38-05, ordered, 1145, 2800.00, 447.06, 0.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '0.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 896636, tzinfo=<UTC>), 'order_number': 1145, 'status': 'ordered', 'tax': '447.06', 'client_id': None, 'created_by': 1, 'date': '2018-09-17T20:17:38-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 896612, tzinfo=<UTC>), 'total': '2800.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
596036649011,(psycopg2.IntegrityError) null value in column "client_id" violates not-null constraint
DETAIL:  Failing row contains (162, 2018-09-18 16:22:20.840224-05, 1, 2018-09-18 16:22:20.84027-05, 0, 5, null, 2018-09-17 20:00:28-05, ordered, 1144, 22900.00, 3656.30, 3000.00).
 [SQL: 'INSERT INTO "order" (created_at, created_by, updated_at, updated_by, seller_id, client_id, date, status, order_number, total, tax, shipping) VALUES (%(created_at)s, %(created_by)s, %(updated_at)s, %(updated_by)s, %(seller_id)s, %(client_id)s, %(date)s, %(status)s, %(order_number)s, %(total)s, %(tax)s, %(shipping)s) RETURNING "order".id'] [parameters: {'updated_by': 0, 'shipping': '3000.00', 'seller_id': 5, 'updated_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 840270, tzinfo=<UTC>), 'order_number': 1144, 'status': 'ordered', 'tax': '3656.30', 'client_id': None, 'created_by': 1, 'date': '2018-09-17T20:00:28-05:00', 'created_at': datetime.datetime(2018, 9, 18, 21, 22, 20, 840224, tzinfo=<UTC>), 'total': '22900.00'}] (Background on this error at: http://sqlalche.me/e/gkpj)
593491296307,The phone number into order is not a valid number
593464393779,The phone number into order is not a valid number
